# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Andreas A. Buchheit

"""Frozen executor outputs — the acceptance instrument for engine
refactors.

A refactor that moves arithmetic between modules promises that *no
value moves*.  That promise needs an instrument, because the suite's
existing cross-engine gates cannot supply one: the torus-vs-SP-algebra
comparison gates at 1e-10 and measures 4.06e-13, the torus-vs-``graph_sample``
comparison gates at 1e-10 and measures 3.32e-15.  A genuine defect in the
shared executor would sit two to four orders *inside* those gates and
never surface.  So the values are frozen here at their exact float64
bits, and each record carries the tolerance its engine is entitled to.

The freeze set lives in ``fixtures/executor_goldens.json`` and is
regenerated by ``fixtures/_freeze_executor_goldens.py``.  Re-freezing is
a deliberate act: it resets the reference that any refactor in progress
is checked against, so it belongs in its own commit with the reason
stated.

**Bit-identity is a same-environment property, and this file does not
pretend otherwise.**  ``numpy``'s ``power``, ``cos`` and FFT reduce
differently across libm, BLAS and SIMD builds: 14 of the 41 records
differ between macOS/Accelerate and the Linux CI runner, by 1 to 8 ulp.
The pattern is *not* the BLAS-matmul one that
``tests/test_direct_sum_lazy.py`` isolates — a diagonal d = 2 lattice
and several d = 1 records diverge while the skew d = 2 record does not
— so it cannot be narrowed to a subset and excluded.  Records gated
``exact`` are therefore compared bitwise **only in the environment the
freeze was made in**, and against a calibrated 64-ulp bound elsewhere.
The consequence is stated by ``test_which_gate_this_environment_runs``
on every run: a green CI does not certify bit-identity.  Run the suite
on the freezing machine for that — which is where a refactor must be
checked.

Three properties of the freeze set are themselves asserted here, because
a golden file that cannot reach the code under test certifies nothing:

* every executor the frontend routes to appears (:class:`TestCoverage`);
* the FFT peel actually executes — at d = 1 only under a forced gate,
  since ``_conv_possible`` is False at every shipped d = 1 rung
  (:class:`TestAntiVacuity`);
* the forced-gate records really do take a different code path from
  their default-gate twins, rather than silently re-running the same
  arithmetic under a flag nothing reads.

``nu = inf`` records carry an extra, engine-independent gate: the value
counts nearest-neighbour homomorphisms, so it must be an exact integer
and the peel must not fire.  That check survives a re-freeze — a
regenerated golden could launder ``6.0 -> 5.999999999999999`` past the
bit comparison, but not past integrality.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
import pytest

import gzl.direct_sum as ds
import gzl.tensor_network as tn

_FIXTURES = Path(__file__).parent / "fixtures"
_GOLDEN_PATH = _FIXTURES / "executor_goldens.json"


def _load_freezer():
    """Import the regeneration script as a module (it is not a package)."""
    spec = importlib.util.spec_from_file_location(
        "_freeze_executor_goldens", _FIXTURES / "_freeze_executor_goldens.py",
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_freezer = _load_freezer()
_PAYLOAD = json.loads(_GOLDEN_PATH.read_text())
RECORDS = _PAYLOAD["records"]
BY_LABEL = {r["label"]: r for r in RECORDS}

# --- which gate this environment is entitled to run ------------------------
#
# Bit-identity is a property of the environment, not of this library.
# numpy's power, cos and FFT reduce differently across libm, BLAS and
# SIMD builds: 14 of these 41 records differ between macOS/Accelerate
# and the Linux CI runner, by 1 to 8 ulp.  The pattern is not the
# BLAS-matmul one that tests/test_direct_sum_lazy.py isolates — a
# *diagonal* d = 2 lattice and several d = 1 records diverge, while the
# skew d = 2 record does not — so it cannot be narrowed to a subset of
# records and excluded.
#
# The cross-environment bound is therefore CALIBRATED, not chosen.
# Measured, over this record set:
#
#     cross-platform noise            1 -  8 ulp
#     _USE_CONV off (torus)                848 ulp   <- smallest real defect
#     torus mixed orientation            1.4e11 ulp
#     hybrid orientation fix off         8.3e11 ulp
#     marker rule / box kill switch      5.7e15 ulp
#
# 64 ulp sits 8x above the noise and 13x below the smallest real defect.
# What it gives up is stated plainly rather than hidden: a pure
# reassociation moves 3 ulp (reversed dense factor order) to 6 ulp (a
# 1-ulp kernel exponent), so those are invisible to the portable gate —
# they are the same size as the platform noise, and no cross-platform
# comparison can separate them.  They ARE caught on the freezing
# machine, which is where a refactor must be checked.
CROSS_ENV_ULP = 64.0
_FROZEN_ON = _PAYLOAD.get("fingerprint", {})
SAME_ENV = _FROZEN_ON == _freezer.fingerprint()

# Handle on this module, so the two gate branches can each be forced and
# exercised regardless of which environment the suite happens to run in.
_mod = sys.modules[__name__]

# Executors the frontend can reach.  Anything routable and absent here is
# an unfrozen engine, which is the gap this file exists to close.
ROUTABLE = {
    "direct_sum_zero_momentum",
    "_direct_sum_open_terminal",
    "direct_sum_extrapolated",
    "_direct_sum_extrapolated_grid",
    "graph_zeta_general",
    "graph_zeta_general_at_zero",
    "hybrid_zeta",
}


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------

def _deviation(got, want):
    """Return ``(bit_identical, max_rel, max_ulp)`` for a value pair.

    ``max_rel`` is scaled by the largest golden magnitude rather than
    elementwise, so a near-zero entry cannot manufacture a huge ratio out
    of a last-bit difference.  ``max_ulp`` stays elementwise, since that
    is the quantity the cross-environment ulp bound is written in.
    """
    got = np.asarray(got)
    want = np.asarray(want)
    assert got.shape == want.shape, f"shape moved: {got.shape} vs {want.shape}"
    identical = np.array_equal(got, want)
    diff = np.abs(got - want)
    scale = np.max(np.abs(want)) if want.size else 0.0
    max_rel = float(np.max(diff) / scale) if scale > 0 else float(np.max(diff))
    spacing = np.spacing(np.abs(np.asarray(want, dtype=np.complex128).real))
    spacing = np.maximum(spacing, np.finfo(float).tiny)
    max_ulp = float(np.max(diff / spacing))
    return identical, max_rel, max_ulp


def _check(rec, got):
    want = _freezer._decode(rec["value"])
    identical, max_rel, max_ulp = _deviation(got, want)
    tol = rec["tol"]
    if tol["kind"] == "exact":
        if _mod.SAME_ENV:
            assert identical, (
                f"{rec['label']}: value moved off its frozen bits "
                f"(max_rel={max_rel:.3e}, max_ulp={max_ulp:.1f}). This "
                f"engine is gated bit-identical in the environment the "
                f"freeze was made in; a tolerance here would hide exactly "
                f"the class of defect the freeze exists to catch."
            )
        else:
            assert max_ulp <= CROSS_ENV_ULP, (
                f"{rec['label']}: max_ulp={max_ulp:.1f} > {CROSS_ENV_ULP} "
                f"across environments (frozen on {_FROZEN_ON}, running on "
                f"{_freezer.fingerprint()}). Platform noise measured 1-8 "
                f"ulp and the smallest real defect 848 ulp, so this is "
                f"far outside round-off — treat it as a defect, not as a "
                f"tolerance to widen."
            )
    elif tol["kind"] == "relative":
        assert max_rel <= tol["rtol"], (
            f"{rec['label']}: max_rel={max_rel:.3e} > {tol['rtol']:.1e}"
        )
    elif tol["kind"] == "ulp":
        assert max_ulp <= tol["n_ulp"], (
            f"{rec['label']}: max_ulp={max_ulp:.1f} > {tol['n_ulp']}"
        )
    else:                                        # pragma: no cover
        raise AssertionError(f"unknown tolerance kind {tol['kind']!r}")
    return max_rel, max_ulp


# ---------------------------------------------------------------------------

@pytest.mark.parametrize("label", [r["label"] for r in RECORDS])
def test_golden_reproduces(label):
    """Re-running a frozen input reproduces its frozen output."""
    rec = BY_LABEL[label]
    _check(rec, _freezer.run_record(rec))


class TestCoverage:
    """The freeze set must span what the pipeline actually runs.

    A d = 1 / orthogonal-only freeze is vacuous for both the orientation
    and the truncation defect classes, and every ``n_points`` this repo
    uses (16, 24, 32, 128, 256) is even — so an even-``n`` skew cell is
    mandatory, not decorative.
    """

    def test_every_routable_executor_is_frozen(self):
        frozen = {r["executor"] for r in RECORDS}
        assert ROUTABLE - frozen == set(), (
            f"unfrozen executors: {sorted(ROUTABLE - frozen)}"
        )
        assert frozen - ROUTABLE == set(), (
            f"frozen but not routable: {sorted(frozen - ROUTABLE)}"
        )

    def test_covers_d1_d2_d3(self):
        dims = {len(r["A"]) for r in RECORDS}
        assert {1, 2, 3} <= dims, f"missing dimensions: {{1,2,3}} - {dims}"

    def test_covers_even_n_on_a_skew_cell(self):
        """The orientation defect was invisible at odd n and square A."""
        hits = []
        for r in RECORDS:
            A = np.asarray(r["A"], dtype=float)
            if A.shape[0] < 2:
                continue
            off_diagonal = np.any(np.abs(A - np.diag(np.diag(A))) > 0)
            n = r["kwargs"].get("n_points")
            if off_diagonal and n is not None and n % 2 == 0:
                hits.append(r["label"])
        assert hits, "no even-n record on a non-diagonal lattice"

    def test_covers_a_d3_block(self):
        assert [r["label"] for r in RECORDS if len(r["A"]) == 3]

    def test_every_frozen_executor_is_reached_in_production(self):
        """No record freezes an engine the pipeline cannot get to.

        ``executor_reach`` is derived from the capture at freeze time,
        not written by hand, so this compares the freeze set against
        what the frontend was *observed* doing rather than against a
        list someone maintained.
        """
        unreached = sorted({r["label"] for r in RECORDS
                            if r["executor_reach"] == "unreached"})
        assert not unreached, (
            f"frozen but unreachable from the frontend: {unreached}. "
            f"Either routing changed, or the capture sweep no longer "
            f"covers the order/lattice that reaches them."
        )

    def test_the_capture_saw_every_executor_the_frontend_names(self):
        observed = set(_PAYLOAD["observed_executors"])
        # _direct_sum_open_terminal and direct_sum_zero_momentum are
        # inner calls; the frontend never names them.
        named = ROUTABLE - set(_freezer._INNER_OF)
        assert named <= observed, f"never observed: {sorted(named - observed)}"

    def test_captured_records_exist_for_the_ladders_that_ship(self):
        """At least one record per engine has verbatim production params."""
        captured = {r["executor"] for r in RECORDS
                    if r["origin"] == "captured"}
        for name in ("direct_sum_extrapolated", "_direct_sum_extrapolated_grid",
                     "hybrid_zeta"):
            assert name in captured, f"{name} has no captured-origin record"


class TestAntiVacuity:
    """Assert the freeze set reaches the branches a refactor rewrites."""

    @staticmethod
    def _peel_counts(rec):
        counts = {"box": 0, "torus": 0}
        real_box, real_torus = ds._fft_conv_step, tn._peel_convolution

        def box(*a, **kw):
            counts["box"] += 1
            return real_box(*a, **kw)

        def torus(*a, **kw):
            counts["torus"] += 1
            return real_torus(*a, **kw)

        ds._fft_conv_step = box
        tn._peel_convolution = torus
        try:
            _freezer.run_record(rec)
        finally:
            ds._fft_conv_step = real_box
            tn._peel_convolution = real_torus
        return counts

    def test_box_peel_executes_somewhere(self):
        total = sum(self._peel_counts(r)["box"] for r in RECORDS)
        assert total > 0, "no record executes the box FFT step"

    def test_torus_peel_executes_somewhere(self):
        total = sum(self._peel_counts(r)["torus"] for r in RECORDS)
        assert total > 0, "no record executes the torus FFT step"

    @pytest.mark.parametrize("label", [r["label"] for r in RECORDS
                                       if r["label"].startswith("box_peel_")])
    def test_forced_gate_records_actually_peel(self, label):
        """Without the override these never reach the FFT step at d = 1.

        ``_conv_possible(2L+1, 2L+1, 1)`` is False for L = 4..14 and the
        shipped d = 1 ladder tops out at ``n_full = 17``, so the default
        gate is shut across the whole shipped range.
        """
        assert self._peel_counts(BY_LABEL[label])["box"] >= 1

    def test_default_gate_is_shut_at_d1(self):
        """The premise the forced records exist to work around."""
        for L in range(4, 15):
            assert not ds._conv_possible(2 * L + 1, 2 * L + 1, 1), (
                f"gate open at d=1 L={L}; the box_peel_* records are no "
                f"longer needed for d=1 coverage — re-check before deleting"
            )

    @pytest.mark.parametrize("forced,default", [
        ("box_peel_k4_d1_L6", "box_raw_k4_d1_L6"),
        ("box_peel_k4_d1_L6_finitek", "box_raw_k4_d1_L6_finitek"),
        ("box_peel_k4_d3_cubic_L2", "box_raw_k4_d3_cubic_L2"),
        ("box_peel_open_k4_d1_L5", "box_open_k4_d1_L5"),
    ])
    def test_forced_and_default_take_different_paths(self, forced, default):
        """The override must change the arithmetic, not just a flag.

        This is the flag-half detector: if ``module_globals`` stopped
        reaching the executor, every ``box_peel_*`` golden would still
        pass — it would simply have re-frozen the dense path under a
        peel-shaped name.
        """
        a = np.asarray(_freezer.run_record(BY_LABEL[forced]))
        b = np.asarray(_freezer.run_record(BY_LABEL[default]))
        assert not np.array_equal(a, b), (
            f"{forced} and {default} are bit-identical: the forced gate "
            f"is not reaching the executor"
        )

    def test_forced_and_default_agree_on_the_value(self):
        """…while still computing the same number, to round-off."""
        for forced, default in (("box_peel_k4_d1_L6", "box_raw_k4_d1_L6"),
                                ("box_peel_prism_d1_L5",
                                 "box_raw_prism_d1_L5"),
                                ("box_peel_k4_d3_cubic_L2",
                                 "box_raw_k4_d3_cubic_L2")):
            a = complex(_freezer.run_record(BY_LABEL[forced]))
            b = complex(_freezer.run_record(BY_LABEL[default]))
            assert abs(a - b) <= 1e-13 * abs(b), f"{forced} vs {default}"


class TestBoxEmptyBucketIsUnreached:
    """The empty-bucket branch stays unreachable on the shipped schedules.

    A bucket-less marker vertex must contribute the *full* axis count,
    not the half-axis size — using the latter scales the whole block by
    (L+1)/(2L+1) with no exception, no NaN and no shape signal, and
    every downstream Richardson fit converges happily to the halved
    number.  The branch is unreachable twice over: the label-convention
    unification compresses gap labels away at every public entry (a
    vertex with an incident kernel provably has a non-empty bucket at
    its own elimination), and below that boundary
    ``_min_degree_order`` eliminates degree-0 free vertices before
    ``marker = elimination[-1]`` — the second being a property of the
    *order*, so any cost-ordered schedule would make it live again.

    Two things follow, and both are asserted here rather than argued.
    First, the goldens do **not** guard this branch — a mutation that
    breaks it moves no frozen value, so nobody should read a green
    golden run as covering it.  Second, the day this count stops being
    zero, the freeze set silently loses whatever coverage the planner
    adoption assumed it had.
    """

    @staticmethod
    def _count_hits():
        """Count empty-bucket dispatches across every box golden.

        The branch now lives in the shared skeleton
        (``_contract.eliminate_one``), which reports it by calling the
        truncation's ``empty_bucket_scalar`` — so wrapping that method
        on ``BoxTruncation`` counts exactly the dispatches the old
        source-splice instrumentation counted, without re-exec'ing any
        module source.  (The previous version spliced a counter into
        ``direct_sum.py`` at the branch's source line; that technique
        broke — loudly, via its own anchor assert — when the branch
        moved, which is what this rewrite answers.)
        """
        hits = []
        real = ds.BoxTruncation.empty_bucket_scalar

        def counting(self, v):
            hits.append(v)
            return real(self, v)

        ds.BoxTruncation.empty_bucket_scalar = counting
        try:
            for rec in RECORDS:
                if rec["executor"].startswith(("direct_sum", "_direct_sum")):
                    _freezer.run_record(rec)
        finally:
            ds.BoxTruncation.empty_bucket_scalar = real
        return hits

    def test_the_hook_is_live(self, monkeypatch):
        """A zero-expected sentinel needs a liveness control: a
        disconnected hook is indistinguishable from an unreached
        branch.  A gap-labelled edge list reaches the branch by
        construction (labels 1 and 3 are degree-0 free vertices) —
        BELOW the label normalisation, which since the label-convention
        unification compresses gaps away at the public entry
        (gzl/_labels.py).  The normalisation is bypassed here,
        for this probe only, so the control still drives the engine
        exactly the way the pre-unification public entry did."""
        monkeypatch.setattr(ds, "_relabel_to_support",
                            lambda edges, refs=None: (edges, refs))
        hits = []
        real = ds.BoxTruncation.empty_bucket_scalar

        def counting(self, v):
            hits.append(v)
            return real(self, v)

        ds.BoxTruncation.empty_bucket_scalar = counting
        try:
            ds.direct_sum_zero_momentum(
                np.array([[0, 2], [2, 4]]), np.full(2, 2.5),
                np.eye(1), 3, root=0)
        finally:
            ds.BoxTruncation.empty_bucket_scalar = real
        assert len(hits) == 2, (
            f"the counting wrapper saw {len(hits)} empty buckets on an "
            f"input that must produce exactly 2; the hook is dead and "
            f"test_branch_fires_zero_times is vacuous"
        )

    def test_branch_fires_zero_times(self):
        hits = self._count_hits()
        assert hits == [], (
            f"the box empty-bucket branch became reachable ({len(hits)} "
            f"hits, vertices {hits}). That is not a failure in itself — "
            f"the branch is correct — but it means the elimination order "
            f"changed, and the bit-preservation argument for the "
            f"empty-bucket fix rested on the branch never firing."
        )


class TestKernelEvennessPremise:
    """Where an orientation slip can and cannot be seen.

    The torus kernel is even — ``K == reverse(K)`` exactly — on every
    diagonal lattice and at every odd ``n``.  On those inputs a reversed
    edge is a no-op, so no golden built from them can detect an
    orientation defect.  The property is measured here rather than
    assumed, because it is the entire justification for carrying skew
    cells at even ``n`` in the freeze set.
    """

    @pytest.mark.parametrize("A,n,nu", [
        (np.eye(1), 16, 2.5),
        (np.eye(2), 8, 3.0),
        (np.array([[1.0, 0.5], [0.0, float(np.sqrt(3) / 2)]]), 7, 3.0),
        (np.eye(3), 6, 4.5),
    ])
    def test_kernel_is_even_where_orientation_cannot_matter(self, A, n, nu):
        K = tn._edge_kernel_torus(nu, A, n)
        assert np.array_equal(K, tn._reverse_generator(K))

    @pytest.mark.parametrize("A,n,nu,floor", [
        (np.array([[1.0, 0.5], [0.0, float(np.sqrt(3) / 2)]]), 8, 3.0, 1e-3),
        (np.array([[1.0, 0.3, 0.1], [0.0, 1.2, 0.2], [0.1, 0.0, 0.9]]),
         6, 4.5, 1e-4),
    ])
    def test_kernel_is_not_even_on_the_records_that_exist_for_it(
            self, A, n, nu, floor):
        K = tn._edge_kernel_torus(nu, A, n)
        dev = np.max(np.abs(K - tn._reverse_generator(K))) / np.max(np.abs(K))
        assert dev > floor, (
            f"non-evenness fell to {dev:.3e}: the skew even-n records no "
            f"longer distinguish an orientation defect from a no-op"
        )

    def test_a_mixed_orientation_flip_moves_a_frozen_value(self):
        """The detector, end to end.

        A *global* flip is the x -> -x inversion, which zeta preserves —
        so it is not a usable mutation.  Flipping only some edges is the
        real defect class, and it must move a bit-identical golden.
        """
        rec = BY_LABEL["tn_k4_d2_tri_n8"]
        real = tn._edge_difference_table
        seen = {"n": 0}

        def alternating(K, n):
            seen["n"] += 1
            return (real(tn._reverse_generator(K), n) if seen["n"] % 2
                    else real(K, n))

        # Compared against a freshly computed baseline, not the frozen
        # bits: on an environment where this record already differs from
        # the freeze by round-off, comparing to the file would pass
        # whether or not the mutation did anything.
        baseline = np.asarray(_freezer.run_record(rec))
        tn._edge_difference_table = alternating
        try:
            got = np.asarray(_freezer.run_record(rec))
        finally:
            tn._edge_difference_table = real
        assert seen["n"] >= 2, "the mutation never reached the executor"
        assert not np.array_equal(got, baseline)
        rel = float(np.max(np.abs(got - baseline)) / np.max(np.abs(baseline)))
        assert rel > 1e-8, (
            f"a mixed orientation flip moved the value only {rel:.3e} — "
            f"this record can no longer distinguish the defect class"
        )


class TestNuInfIntegrality:
    """``nu = inf`` counts nearest-neighbour homomorphisms.

    The value is therefore an exact non-negative integer, independently
    of any frozen bits.  An FFT round trip returns 6.0 as
    5.999999999999999, so integrality plus a zero peel count catches a
    misrouted kernel that a re-frozen golden would happily absorb.
    """

    LABELS = [r["label"] for r in RECORDS
              if any(np.isinf(x) for x in r["nu"])]

    def test_there_is_at_least_one(self):
        assert self.LABELS

    @pytest.mark.parametrize("label", LABELS)
    def test_value_is_an_exact_integer(self, label):
        val = np.asarray(_freezer.run_record(BY_LABEL[label])).real
        assert np.array_equal(val, np.round(val)), (
            f"{label}: nu=inf gave a non-integral value {val}"
        )
        assert np.all(val >= 0)

    @pytest.mark.parametrize("label", LABELS)
    def test_peel_does_not_fire(self, label):
        counts = TestAntiVacuity._peel_counts(BY_LABEL[label])
        assert counts["box"] == 0 and counts["torus"] == 0, (
            f"{label}: the FFT path must opt out of an inf kernel"
        )

    def test_the_closed_form_is_what_we_froze(self):
        """Independent of the engine: closed NN walks of length 4 on Z^d.

        A 4-cycle rooted at the origin embeds as a closed 4-step
        nearest-neighbour walk.  On Z^1 there are C(4,2) = 6 of them; the
        d-dimensional count is the coefficient extraction over the 2d
        unit steps, which for d = 2 gives 36.
        """
        val1 = np.asarray(_freezer.run_record(
            BY_LABEL["tn_c4_d1_n32_inf"])).real
        val2 = np.asarray(_freezer.run_record(
            BY_LABEL["tn_c4_d2_n8_inf"])).real
        assert float(val1) == 6.0
        assert float(val2) == 36.0


class TestOpenTerminalSymmetrisation:
    """Why the open-terminal residual may be odd-looking and still right.

    ``_direct_sum_open_terminal`` folds one *free* vertex onto a half box
    under the global x -> -x inversion.  That inversion also flips the
    terminal, so for a fixed ``x_terminal`` the fold does not close on
    itself: the returned ``M`` is **not** even, and only its
    symmetrisation equals the true residual.

    The caller's cosine transform performs that symmetrisation
    implicitly, which is why every published value is unaffected — but
    the property is worth pinning, because ``M != M[::-1]`` looks exactly
    like a bug to anyone who checks, and the docstring used to claim the
    returned array was even.
    """

    K4 = np.array([[0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 3]])
    NU = np.full(6, 2.5)

    def _both(self, A, L, d):
        em = ds._collapse_multi_edges(self.K4, self.NU)
        M_marker, pos = ds._direct_sum_open_terminal(
            em, A, L, 0, 3, d, use_symmetry=True)
        M_plain, _ = ds._direct_sum_open_terminal(
            em, A, L, 0, 3, d, use_symmetry=False)
        return M_marker, M_plain, pos

    # Flattened C-order over a symmetric [-L, L]^d grid, so reversing the
    # flat axis *is* the x -> -x map in every d.
    LATTICES = [(np.eye(1), 5, 1),
                (np.array([[1.0, 0.5], [0.0, float(np.sqrt(3) / 2)]]), 3, 2)]

    @pytest.mark.parametrize("A,L,d", LATTICES)
    def test_unfolded_residual_is_even(self, A, L, d):
        _, M_plain, _ = self._both(A, L, d)
        dev = np.max(np.abs(M_plain - M_plain[::-1])) / np.max(np.abs(M_plain))
        assert dev <= 1e-14, f"unfolded residual is not even: {dev:.3e}"

    @pytest.mark.parametrize("A,L,d", LATTICES)
    def test_marker_residual_is_not_even_but_symmetrises(self, A, L, d):
        M_marker, M_plain, _ = self._both(A, L, d)
        asym = (np.max(np.abs(M_marker - M_marker[::-1]))
                / np.max(np.abs(M_marker)))
        # Structural, not round-off: measured 0.66 at d=1 and 0.50 at
        # d=2.  Requiring it to be large is what stops this test from
        # passing vacuously if the Z2 fold silently stopped happening.
        assert asym > 1e-3, (
            f"the marker fold no longer breaks evenness ({asym:.3e}) — if "
            f"the engine changed, this test's premise is stale, and so is "
            f"the note in _direct_sum_open_terminal's docstring"
        )
        sym = 0.5 * (M_marker + M_marker[::-1])
        assert np.max(np.abs(sym - M_plain)) <= 1e-14 * np.max(np.abs(M_plain))

    @pytest.mark.parametrize("k", [0.0, 0.1, 0.25, 0.3, 0.5])
    def test_cosine_transform_absorbs_the_asymmetry(self, k):
        M_marker, M_plain, pos = self._both(np.eye(1), 5, 1)
        c = np.cos(2.0 * np.pi * k * pos[:, 0])
        a, b = float(c @ M_marker), float(c @ M_plain)
        assert abs(a - b) <= 1e-14 * max(abs(b), 1e-30)

    def test_grid_route_matches_the_single_k_route(self):
        """End-to-end: the asymmetry never reaches a published value."""
        A, L_list = np.eye(1), (4, 5, 6)
        kk = np.array([[0.0], [0.25], [0.5]])
        grid = np.asarray(ds._direct_sum_extrapolated_grid(
            self.K4, self.NU, A, kk, root=0, terminal=3,
            L_list=L_list, n_correction_terms=2)).real
        for i, k in enumerate(kk):
            single = complex(ds.direct_sum_extrapolated(
                self.K4, self.NU, A, L_list=L_list, n_correction_terms=2,
                root=0, terminal=3, momentum=k)).real
            assert abs(grid[i] - single) <= 1e-13 * abs(single)


class TestTheFallbackGateItself:
    """Exercise the cross-environment branch wherever the suite runs.

    On the freezing machine the fallback is dead code and on CI the
    strict branch is; neither would ever be tested by simply running
    the suite.  Both are forced here.
    """

    @staticmethod
    def _self_frozen(label):
        """A record whose frozen value is what this machine just computed.

        Lets the strict branch be tested for its *logic* — accepts an
        identical value, rejects a 1-ulp perturbation — without needing
        the running environment to be the freezing one.  Asserting the
        real records bitwise off-platform could only ever fail, which is
        the property under test, not a bug to assert around.
        """
        rec = dict(BY_LABEL[label])
        got = np.asarray(_freezer.run_record(rec)).real
        rec["value"] = _freezer._encode(got)
        return rec, got

    def test_strict_branch_accepts_an_identical_value(self, monkeypatch):
        monkeypatch.setattr(_mod, "SAME_ENV", True)
        rec, got = self._self_frozen("box_raw_k4_d1_L6")
        _check(rec, got)

    def test_strict_branch_rejects_one_ulp(self, monkeypatch):
        """What the strict gate buys over the portable one."""
        monkeypatch.setattr(_mod, "SAME_ENV", True)
        rec, got = self._self_frozen("box_raw_k4_d1_L6")
        with pytest.raises(AssertionError, match="moved off its frozen bits"):
            _check(rec, np.nextafter(got, np.inf))

    def test_fallback_branch_tolerates_one_ulp_but_not_a_thousand(
            self, monkeypatch):
        monkeypatch.setattr(_mod, "SAME_ENV", False)
        rec, got = self._self_frozen("box_raw_k4_d1_L6")
        nudged = got
        for _ in range(4):
            nudged = np.nextafter(nudged, np.inf)
        _check(rec, nudged)                       # 4 ulp: inside the bound
        far = got
        for _ in range(int(CROSS_ENV_ULP) + 8):
            far = np.nextafter(far, np.inf)
        with pytest.raises(AssertionError, match="across environments"):
            _check(rec, far)

    def test_fallback_still_fails_on_a_real_defect(self, monkeypatch):
        """The bound must not be so loose that it stops discriminating.

        Measured: platform noise tops out at 8 ulp, the *smallest* real
        defect in the mutation set (turning the torus FFT peel off)
        moves 848 ulp.  64 sits between them with 8x and 13x margin.
        """
        monkeypatch.setattr(_mod, "SAME_ENV", False)
        monkeypatch.setattr(tn, "_USE_CONV", False)
        failures = 0
        for rec in RECORDS:
            if rec["executor"] not in ("graph_zeta_general",
                                       "graph_zeta_general_at_zero"):
                continue
            try:
                _check(rec, _freezer.run_record(rec))
            except AssertionError:
                failures += 1
        assert failures >= 1, (
            "the cross-environment bound no longer catches a disabled "
            "torus FFT peel; it has been widened past the point of use"
        )


def test_which_gate_this_environment_runs(capsys):
    """Say out loud which gate ran, so a green run is never misread.

    In the freezing environment the ``exact`` records are compared
    bitwise.  Anywhere else they fall back to a calibrated ulp bound,
    and a pure reassociation — the very thing a refactor must
    not introduce — is *below* that bound.  A CI-only green therefore
    does not certify bit-identity, and this line is what stops someone
    concluding that it does.
    """
    mode = "BIT-IDENTICAL (freezing environment)" if SAME_ENV else \
        f"{CROSS_ENV_ULP:.0f}-ulp fallback (different environment)"
    with capsys.disabled():
        print(f"\n  exact-gated records run under: {mode}")
        print(f"    frozen on: {_FROZEN_ON}")
        print(f"    running on: {_freezer.fingerprint()}")
        if not SAME_ENV:
            print("    -> a <=64 ulp reassociation would NOT be caught here; "
                  "run the suite on the freezing environment for that.")
    assert isinstance(SAME_ENV, bool)


def test_encoding_round_trips_exactly():
    """``float.hex`` must not be a lossy channel for the frozen bits."""
    rng = np.random.default_rng(0)
    for value in (np.float64(0.0), np.float64(-0.0), np.float64(1e-320),
                  rng.standard_normal(17),
                  rng.standard_normal(5) + 1j * rng.standard_normal(5)):
        again = _freezer._decode(_freezer._encode(value))
        assert np.array_equal(np.asarray(value), again)
        assert np.signbit(np.asarray(value).real).tolist() == \
            np.signbit(again.real).tolist()

